# Site settings
title: Working in the open with W3C and Studio 24
email: carlos@studio24.net
description: > # this means to ignore newlines until "baseurl:"
  Global page description
baseurl: ""
url: "https://w3c.studio24.net"
theme: just-the-docs
color_scheme: nil

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; footer copy"

collections:
  docs:
    output: true
    permalink: /docs/:title/

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /updates/:title/
future: false

# Sass settings
sass:
    style:  compressed  # nested|expanded|compact|compressed
    deploy_style: compressed  # nested|expanded|compact|compressed
    # "deploy_style:" is used only for building the site
    # (ie: not using the --watch flag)

    compile_in_place: false   # true|false
    # If true, compiles sass directly into your jekyll source directory
    # As well as your destination directory

plugins:
- jekyll-seo-tag
